### PR TITLE
fix typos and links for week 1-3 in class notebook and assignment

### PR DESCRIPTION
**Pull request by duserzym**

### CODE REVIEW

**Comment by duserzym** [comment]
One thing we could think to bring in week 3 assignment is to use geopy.distance.distance to calculate distance between earthquake location and seismic state location rather than bringing the numbers to the NOAA website (although we can keep the website link in there!). 

https://geopy.readthedocs.io/en/stable/#module-geopy.distance

**Comment by duserzym** [comment]
The link in week 3 in class notebook for 2011 Tōhoku earthquake is dead. I edited to be this one: https://www.youtube.com/watch?v=oWzdgBNfhQU

**Comment by Swanson-Hysell** [comment]
If we use ```geopy```, we would need to make sure that the module can be used with the Datahub Jupyterhub — I can ask for it to be installed on there.

**Comment by duserzym** [comment]
I tried `from geopy import distance` in W3 assignment on my Jupyterhub and it worked! Jupyterhub already added this package!

**Comment by Swanson-Hysell** [comment]
Excellent. It will be much better to us that package than to send to external NOAA website. Have you integrated it into the Week 3 notebook? We should be sure to include a bit of discussion about the package/function in the markdown.

**Pull request merged**
